export const SIGN_IN_EMAIL_CHANGED = "SIGN_IN_EMAIL_CHANGED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_USERID = "SET_USERID";
export const PROFILE_COMPLETE = "PROFILE_COMPLETE";
export const UPDATE_HOSTING_EVENT = "UPDATE_HOSTING_EVENT";
export const UPDATE_ATTENDING_EVENT = "UPDATE_ATTENGING_EVENT";
